FROM openjdk:17
COPY SignaTgBot-1.0-SNAPSHOT-jar-with-dependencies.jar SignaTgBot-1.0-SNAPSHOT-jar-with-dependencies.jar
CMD java -jar /SignaTgBot-1.0-SNAPSHOT-jar-with-dependencies.jar --api.key=${API_KEY} --api.secret=${API_SECRET} --api.url=${API_URL} --bot.key=${BOT_KEY} --channel.id=${CHANNEL_ID} --admin.chat.id=${ADMIN_CHAT_ID} --mongo.db.url=${MONGO_DB_URL}